FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 8000
CMD ["python", "-m", "gunicorn", "ghostbusters_wiki.wsgi:app", "-b", "0.0.0.0:8000"]
