[project]
name = "ghostbusters_wiki"
version = "0.1.0"
description = "Test app to try out Proton Pack"
dependencies = [
    "flask"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"