from typing import List

from sqlglot import exp, parse, parse_one


# Parse multiple SQL statements into its AST representation
# Parsed using postgres dialect
def parse_sql_to_ast(sql) -> List[exp.Expression]:
    if sql is None or sql == "":
        return []

    parsed = parse(sql, dialect="postgres")
    filtered = _remove_alembic_specific_statements(parsed)
    return [p for p in filtered if p is not None]


# Parse a single SQL statement into its AST representation
# Parsed using postgres dialect
def parse_sql_line_to_ast(sql: str) -> exp.Expression | None:
    if sql is None or sql == "" or sql.strip().startswith("--"):
        return None

    return parse_one(sql, dialect="postgres")


# SQL statements generated by Alembic (used by frameworks like Flask) should be ignored
# They do not provide any relevant information regarding AST of the target database
def _remove_alembic_specific_statements(ast: List[exp.Expression]) -> List[exp.Expression]:
    filtered = []
    for tree in ast:
        if tree is None:
            continue
        table = tree.find(exp.Table)
        table_name = table.name if table else _extract_table_name_from_expression(tree.expression)

        if table_name and "alembic" not in table_name.lower():
            filtered.append(tree)
    return filtered


def _extract_table_name_from_expression(expression: str) -> str | None:
    expression_words = expression.strip().split(" ")
    filtered_words = [x for x in expression_words if x != " "]
    table_keyword_index = filtered_words.index("TABLE")

    try:
        table_name = filtered_words[table_keyword_index + 1]
    except:
        return None

    return table_name

