"""Initial database schema

Revision ID: 33018f72f5b1
Revises: 
Create Date: 2025-09-21 13:56:19.750553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33018f72f5b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ghosts_table = op.create_table('ghost',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(ghosts_table, [
        {'id': 1, 'name': 'Slimer'},
        {'id': 2, 'name': 'Zuul'}
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ghost')
    # ### end Alembic commands ###
