"""add foreign key to human table

Revision ID: a9c1d391bad5
Revises: af3c701704d2
Create Date: 2026-01-15 17:15:09.681967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c1d391bad5'
down_revision = 'af3c701704d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ghost', schema=None) as batch_op:
        batch_op.alter_column('reporter_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.create_foreign_key(None, 'human', ['reporter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ghost', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('reporter_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###
