"""Update ghost table, add human table

Revision ID: af3c701704d2
Revises: c35a6cb386af
Create Date: 2025-10-24 16:43:08.626600

"""
from alembic import op
import sqlalchemy as sa
from datetime import date


# revision identifiers, used by Alembic.
revision = 'af3c701704d2'
down_revision = 'c35a6cb386af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    human_table = op.create_table('human',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('ghost', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spooky_level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ectoplasm_volume', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('reporter_id', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('danger_rating', sa.Integer(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###

    ghosts_table = sa.table(
        'ghost',
        sa.Column('id', sa.Integer),
        sa.Column('name', sa.Text),
        sa.Column('spooky_level', sa.Integer),
        sa.Column('ectoplasm_volume', sa.BigInteger),
        sa.Column('reporter_id', sa.BigInteger),
        sa.Column('danger_rating', sa.Integer),
    )

    op.bulk_insert(ghosts_table, [
        {'id': 1, 'name': 'Slimer', 'spooky_level': 8, 'ectoplasm_volume': 2500, 'reporter_id': 1, 'danger_rating': 5},
        {'id': 2, 'name': 'Gozer', 'spooky_level': 10, 'ectoplasm_volume': 9000, 'reporter_id': 2, 'danger_rating': 10},
        {'id': 3, 'name': 'Library Ghost', 'spooky_level': 6, 'ectoplasm_volume': 1800, 'reporter_id': 3,
         'danger_rating': 4},
    ])

    op.bulk_insert(human_table, [
        {'id': 1, 'name': 'Peter Venkman', 'email': 'peter@ghostbusters.com', 'hire_date': date(1984, 6, 8)},
        {'id': 2, 'name': 'Egon Spengler', 'email': 'egon@ghostbusters.com', 'hire_date': date(1984, 6, 8)},
        {'id': 3, 'name': 'Ray Stantz', 'email': 'ray@ghostbusters.com', 'hire_date': date(1984, 6, 8)}
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ghost', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
        batch_op.drop_column('danger_rating')
        batch_op.drop_column('reporter_id')
        batch_op.drop_column('ectoplasm_volume')
        batch_op.drop_column('spooky_level')

    op.drop_table('human')
    # ### end Alembic commands ###
