"""Remove weapons table

Revision ID: c35a6cb386af
Revises: f3d7dffbf9a3
Create Date: 2025-10-07 14:05:02.897262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c35a6cb386af'
down_revision = 'f3d7dffbf9a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapon')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('weapon_pkey'))
    )
    # ### end Alembic commands ###
