"""Add weapons table

Revision ID: f3d7dffbf9a3
Revises: 33018f72f5b1
Create Date: 2025-10-07 14:01:57.215439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d7dffbf9a3'
down_revision = '33018f72f5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    weapons_table = op.create_table('weapon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(weapons_table, [
        {'id': 1, 'name': 'Proton Pack'},
        {'id': 2, 'name': 'Slime Blower'}
    ])


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weapon')
    # ### end Alembic commands ###
