name: 'Proton Pack GitHub Action'
description: 'A GitHub Action that analyzes database migration files'
inputs:
  migration_file:
    description: 'Enter a file name'
    required: true
  github_token:
    description: 'GitHub token, required to access GitHub API'
    required: true
outputs:
  analysis_result:
    description: 'An analysis result of the added migrations'
    value: ${{ steps.proton-pack.outputs.analysis_result }}
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install Dependencies
      run: pip install -e .
      shell: bash
    - name: Pass Inputs to Shell
      run: |
              echo "MIGRATION_FILE=${{ inputs.migration_file }}" >> $GITHUB_ENV
      shell: bash
    - name: Run the analyzer
      id: proton-pack
      run: python src/proton_pack/action.py
      shell: bash
    - name: Post result as comment in PR conversation
      uses: actions/github-script@v8
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Proton Pack says Hi 👋'
          })