name: Continuous Integration
on:
  pull_request:
    types: [synchronize]

jobs:
  continuous_integration:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.14
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Test with pytest
        run: |
          pip install pytest
          pytest --cov-fail-under=90
